# Examples

Here are some examples of other GitBooks for courses; if you want to have your GitBook added to the list, please send a [Pull Request](https://github.com/cjvanlissa/gitbook-demo/pulls) (here's [how to send a pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)).

## Statistics with R (H. Quene)

<https://hugoquene.github.io/emlar2020>

A GitBook for a tutorial on *Statistics with R (Basics)*, held as part of the workshop on Experimental Methods in Language Acquisition Research (EMLAR, https://emlar.wp.hum.uu.nl/), Utrecht, on 17 April 2020. This compact introduction helps you with your first steps into R.

## Theory Construction and Statistical Modeling (C. J. van Lissa)

<http://cjvanlissa.github.io/TCSM>

A GitBook for the course *"Theory Construction and Statistical Modeling"*, with some interesting code, for example: Blocks of answers to the tutorial questions that can be collapsed and expanded.

## Doing Meta-Analysis in R (C. J. van Lissa)

<http://cjvanlissa.github.io/Doing-Meta-Analysis-in-R>

A GitBook on doing meta-analysis in R, based on the book ‘Doing Meta-Analysis in R’, by Mathias Harrer, Pim Cuijpers, & David Ebert, and adapted to focus on the [metafor](https://cran.r-project.org/web/packages/metafor/index.html) package, and exploring heterogeneity using [metaforest](https://cran.r-project.org/web/packages/metaforest/index.html). The original can be found here: https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/

## Métodos quantitativos em Psicologia com R (L. Anunciação)

<https://anovabr.github.io/mqt/>

This book provides a short and to-the-point exposition on the essentials of statistics, and was written for undergraduate students at the Pontifical Catholic University of Rio de Janeiro (PUC-Rio). To a lesser degree, the mathematical modeling of statistical questions will be addressed. This book might be relevant for Portuguese-speaking students who enroll for laboratory-based statistics and anyone who wants to learn R.
