--- 
title: "A GitBook Example for Teaching"
author: "dr. Caspar J. van Lissa"
date: "`r Sys.Date()`"
description: This GitBook for teaching is an adaptation of the minimal bookdown
  example by Yihui Xie, available at https://bookdown.org/yihui/bookdown-demo
  The output format for this example is bookdown::gitbook.
documentclass: book
github-repo: cjvanlissa/gitbook-demo
link-citations: yes
bibliography:
- book.bib
- packages.bib
site: bookdown::bookdown_site
biblio-style: apalike
---

# Prerequisites

This GitBook is created in Rstudio, using the `bookdown` package. To get your system set up correctly, I recommend that you follow the installation guide I've written for another package, available [here](https://cjvanlissa.github.io/worcs/articles/setup.html). **NOTE:** You should *skip Step 3* in that guide (it will save you a lot of time), and instead of running the code in *Step 7*, run the following code:

```{r eval=FALSE}
install.packages("bookdown")
install.packages("tinytex")
tinytex::install_tinytex()
git2r::config(global = TRUE, user.name = "your.name", user.email = "your.email")
```

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
