# Open Educational Resources

UNESCO defines Open Educational Resources as [*teaching, learning and research materials in any medium – digital or otherwise – that reside in the public domain or have been released under an open license that permits no-cost access, use, adaptation and redistribution by others with no or limited restrictions.*](https://en.unesco.org/themes/building-knowledge-societies/oer)

Open Educational resources can help lighten the workload on individual teachers, who can collaborate with the development of high-quality open access resources, instead of having to develop their own proprietary materials from scratch. Moreover, Open Educational resources are inclusive, lowering the barrier to knowledge acquisition for learners around the world, and enabling lifelong learning for those outside academia.

Many universities support Open Educational Resources. Here are just a few (feel free to [send a pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) with other relevant resources).

* [__OER Commons__](https://www.oercommons.org/): A freely accessible online library of open educational resources.
* [__Utrecht University Figshare__](https://uu.figshare.com/): Open learning objects from Utrecht University.
* [__Johns Hopkins University OCW__](https://ocw.jhsph.edu/): Open public health courses and materials.
* [__University of Pittsburgh OER__](https://pitt.libguides.com/openeducation/biglist): Big List of Open Educational Resources.
* [__MERLOT__](https://www.merlot.org/merlot/): Online learning and support materials and content creation tools, led by an international community of educators, learners and researchers.
